### ISSUE TITLE
How to run on Raspberry Pi?

### ISSUE THREAD

**Issue by Identifier** [Vansmak/episeerr#8]
When attempting to add this to my docker compose for all my other *arr containers running on my Raspberry Pi, I'm seeing this error:

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Is there any way to run this alongside radarr/sonarr/overseerr on a Raspberry Pi?

Here's my existing docker-compose.yml if it helps in any way:

```
identifier@pi(ro):/mnt/bigssd/containers/servarr$ cat docker-compose.yml 

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./plex/config:/config
      - ./media:/media

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports: ["7878:7878"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr/config:/config
      - ./media/movies:/movies
      - ./media/downloads:/downloads

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports: ["8989:8989"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonarr/config:/config
      - ./media/series:/tv
      - ./media/downloads:/downloads

  episeerr:
    image: vansmak/episeerr:latest
    container_name: episeerr
    restart: unless-stopped
    ports: ["5002:5002"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./episeerr/config:/app/config
      - ./episeerr/logs:/app/logs
    env_file:
      - ./episeerr/.env
    extra_hosts:
      - "pi:host-gateway"

#  maintainerr:
#    image: jorenn92/maintainerr:latest
#    container_name: maintainerr
#    restart: unless-stopped
#    ports: ["6246:6246"]
#    environment:
#      - PUID=1000
#      - PGID=1000
#    volumes:
#      - ./maintainerr/data:/opt/data
#    extra_hosts:
#      - "pi:host-gateway"

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    ports: ["5055:5055"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./overseerr/config:/config
      - ./media:/media
    extra_hosts:
      - "pi:host-gateway"

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports: ["8181:8181"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tautulli/config:/config

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports: ["6980:8080"]
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sabnzbd/config:/config
      - ./media/downloads:/downloads
```
